name: HexFFS # the plugins name as it should appear in the plugin list /pl
version: 1.0 # the plugin's version
author: nejlontacskó
main: hu.steradian.hexffs.mcplugin.Main
api-version: 1.18 # the version of the API you want to use, required starting with 1.13